export const GET_GENRES = 'GET_GENRES';
export const ERROR = 'ERROR'
export const FILTERBYGENRE = "FILTERBYGENRE"
export const GET_ALLMOVIES = 'GET_ALLMOVIES';
export const GET_UPMOVIES = 'GET_UPMOVIES';
export const GET_MOVIEDETAILS = 'GET_MOVIEDETAILS';